### ISSUE TITLE
library missing full bitcode during archive

### ISSUE THREAD

**Issue by sergiodaia** [adform/adform-ios-sdk#1]
I get the following error during archive of my app which includes the adform-ios-sdk:

`bitcode bundle could not be generated because '/anonymous_path_here/AdformAdvertising.framework/AdformAdvertising(AFAdInline.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

**Comment by vladasdrejeris** [comment]
Try to update sdk

**Comment by sergiodaia** [comment]
Resolved. thank you very much
