### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException Invalid number value (infinite) in JSON write

### ISSUE THREAD

**Issue by Gerharbo** [adform/adform-ios-sdk#10]
Hi,

We're testing the AdForm SDK at the moment and we're running into stability issues:
`Fatal Exception: NSInvalidArgumentException: AFAdxAPIClient.m line 87 -[AFAdxAPIClient createUrlRequestFromAdRequest:]`

Stacktrace:
```
0 	CoreFoundation	__exceptionPreprocess
16 	Foundation	+[NSJSONSerialization dataWithJSONObject:options:error:]
17	Appname	AFAdxAPIClient.m line 87 	-[AFAdxAPIClient createUrlRequestFromAdRequest:]
18	Appname	AFAdxAPIClient.m line 46	-[AFAdxAPIClient executeAdRequest:withCompletionHandler:]
19	Appname	AFBaseAdLoader.m line 146	-[AFBaseAdLoader loadRegularAd:]
20	Appname	AFBaseAdLoader.m line 107	-[AFBaseAdLoader loadAd:inDebugMode:]
21	Appname	AFAdInline.m line 845	-[AFAdInline loadAdFromAdx]
22	Appname	AFAdInline.m line 839	-[AFAdInline loadAd]
```
We're using:
AdformAdvertising (2.7.2)

Can you help us out?

Regards,
Gerhard

**Comment by vladasdrejeris** [comment]
Hello, 

Can you show me your implementation of the AFAdInline?

**Comment by Gerharbo** [comment]
@vladasdrejeris do you mean the code?
It's all in Swift 3.1:
```
            self.bannerView = AFAdInline(masterTagId: 1111, presenting: self)
            self.bannerView?.areAditionalDimmensionsEnabled = true
            self.bannerView?.supportedDimmensions = [AFSmartAdSize, CGSize(width: 320, height: 50), CGSize(width: 320, height: 100)]
            self.bannerView?.delegate = self
            self.bannerView?.loadAd()
```
The banner is shown in a UITableViewCell (reuse save).
We're reloading the banner on `UIApplicationDidBecomeActive`.

**Comment by vladasdrejeris** [comment]
I cannot seem to reproduce the crash, but I see one issue in your code, you cannot set AFSmartAdSize to supported dimensions, this is a separate feature of the ad view. Try removing it.

**Comment by Gerharbo** [comment]
I will remove it & try again. The problem is: the crash is inconsistently, it doesn't happen all the time.

**Comment by Gerharbo** [comment]
I'm using CGSize, because `AFAdDimension` isn't available. 

Doucmentation:
https://github.com/adform/adform-ios-sdk/wiki/Advanced-Inline-Ad-Integration#multiple-ad-size-support

**Comment by vladasdrejeris** [comment]
Yes, it's a feature of Swift 3.0 that AFAdDimension is not available. Are you running the app on simulator or real device when it crash'es?

**Comment by vladasdrejeris** [comment]
And what iOS version?

**Comment by Gerharbo** [comment]
No, I was running it as a beta on the device (via TestFlight). Just released a new update. We will find out if AFSmartAdSize is the cause of the problem.

Most of the crashes are from an iPhone running 10.2.1.

**Comment by Gerharbo** [comment]
BTW: thanx for the swift replies!

**Comment by vladasdrejeris** [comment]
No problem, is it working ok now?

**Comment by Gerharbo** [comment]
We're testing at the moment.. I'll update the issue if the problem is solved.

**Comment by Gerharbo** [comment]
After some more testing and removing AFSmartAdSize (and completely removed the previous ads sdk) the app looks stable. We will be testing some more in the upcoming week.

Thanks!
