### ISSUE TITLE
Trouble interacting with interstitial

### ISSUE THREAD

**Issue by sil-visiolink** [adform/adform-ios-sdk#11]
I've encountered an issue, that I haven't been able to resolve, so I'm reaching out to you guys in hopes of finding a solution.

The issue at hand is encountered when I try to interact with an interstitial or simply try to open it by tapping.

I've been debugging a lot, and tried looking through the subviews of AFAdInterstitial to see if there was any reaction at all, when I tapped on the interstitial. I found the AFWebView and set the delegate to my own viewcontroller to see if "shouldStartLoadWithRequest" was called. It was!

But I still can't make any interactions with the interstitial. Do you guys have any idea what could be the cause of that?

**Comment by vladasdrejeris** [comment]
Hi,

What interactions are you talking about? What are you trying to do?

**Comment by sil-visiolink** [comment]
Hi,

I'm just trying to open the embedded link in the interstitial. Even though the web-view delegate is called the AFAdInterstitial delegate: "adInlineDidClick" isn't called. So something is interrupting the click.

**Comment by sil-visiolink** [comment]
I just realised that your sample app is running on the 2.2 version of the SDK, but your newest version is running 2.7.2. The sample app worked fine when tapping on interstitials.

So i tried updating the SDK in the sample app, and now I can't tap on anything. The interstitial is shown but it isn't possible to tap on it to load the URL. So something is wrong with the newest version of your SDK.

**Comment by vladasdrejeris** [comment]
I tried to check it, bet cannot reproduce your issue. Maybe you could make a new simple project that would reproduce you problem and send it to me?

**Comment by sil-visiolink** [comment]
Hi,

I've attached the sample project with the newest SDK and with the masterTag and keyValues from the project I'm working on.

[adform_sample_not_working.zip](https://github.com/adform/adform-ios-sdk/files/986315/adform_sample_not_working.zip)

**Comment by sil-visiolink** [comment]
Could you reproduce it with the project I sent?

**Comment by vladasdrejeris** [comment]
Sorry for delay. I was finally able to take a look at your sample. Which banners are being loaded with you master tag? Because sample project doesn't load any ads in AFAdInterstial for me.

**Comment by sil-visiolink** [comment]
I have created a simple project that loads the interstitial when the viewcontroller is loaded. I still can't interact with the interstitial.

[adform_sample.zip](https://github.com/adform/adform-ios-sdk/files/989096/adform_sample.zip)

**Comment by vladasdrejeris** [comment]
What interactions are you expecting with the ad?

**Comment by sil-visiolink** [comment]
There's 2 interstitials booked in that project I just sent.

The Green one can't be interacted with, but if you touch it, it is supposed to open the embedded URL.

The BMW ad should be able to play the video and change color on the car. It should also be possible to click anywhere else and be directed to the advertiser webpage.

![simulator screen shot 10 may 2017 10 16 08](https://cloud.githubusercontent.com/assets/6650000/25889342/c38fc938-3569-11e7-9c33-41b2aa8774a8.png)
![screen shot 2017-05-10 at 10 15 42](https://cloud.githubusercontent.com/assets/6650000/25889343/c3a92112-3569-11e7-8ebc-74c68e8004be.png)

**Comment by vladasdrejeris** [comment]
Thanks for info, I will try to figure out the problem.

**Comment by vladasdrejeris** [comment]
Try the new 2.8.0 sdk version, it should solve your issues.

**Comment by sil-visiolink** [comment]
Great, that solved it. Thank you!
