### ISSUE TITLE
Please update CocoaPods podspec to support latest release

### ISSUE THREAD

**Issue by michal-maciag** [adform/adform-ios-sdk#13]
Hi, 
we want to use the latest SDK version, but the podspec points to the 2.7.2 instead of 2.8.0. Can you fix this?

**Comment by vladasdrejeris** [comment]
Hello,
The podspec is correct, you should be able to use the latest sdk version with cocopods.

**Comment by michal-maciag** [comment]
Hello, 
thanks it's working now. Previously after 'pod update' I've got 'Using AdformAdvertising (2.7.2)' but today it did fetch new SDK and left the message: 'Installing AdformAdvertising 2.8.0 (was 2.7.2)'. 
Thanks
