### ISSUE TITLE
No issue tab in adform-android-sdk

### ISSUE THREAD

**Issue by sil-visiolink** [adform/adform-ios-sdk#15]
Hi,

We have some trouble implementing the Android SDK, and would like to create an issue under https://github.com/adform/adform-android-sdk, but there's no issues-tab.

So my questions is, can we adress the issue here? Or can you enable the issue-tab?

**Comment by ivenckus** [comment]
Hi,

I have enabled issues tab for Android now as well. Please post your issue

Thanks
