### ISSUE TITLE
Very slow loading times and sometimes it never loads

### ISSUE THREAD

**Issue by sil-visiolink** [adform/adform-ios-sdk#17]
Hi,
 
I am experiencing some loading issues with the AdForm banner.
When I call [AfAdInline loadAd] I often don’t get an answer from your server.
 
I have implemented all the delegate methods and neither adInlineDidFailToLoadAd nor adInlineDidLoadAd is called after loading the ad. Sometimes adInlineDidLoadAd is called after several seconds, but mostly nothing happens.
 
This is how I setup the inline ad:
 
    // Create and setup ad inline view. #143376
    self.adInline = [[AFAdInline alloc] initWithMasterTagId:143376 presentingViewController:self.navigationDelegate];
    self.adInline.additionalDimmensionsEnabled = YES;
    self.adInline.delegate = self;
    [self.adInline setBackgroundColor:[UIColor clearColor]];
    // Set custom position for the ad.
    self.adInline.frame = topView.bounds;
    self.adInline.adSize = CGSizeMake(320, 320);
    [self.adInline setClipsToBounds:YES];
 
 
This is how I load it:
self.adInline.keyValues = AFKeyValuesFromNSDictionary(@{@"prefix": a_customer, @"folder": a_folderId});
        [self.adInline loadAd];
 
Everything is done on the main thread.

**Comment by vladasdrejeris** [comment]
Hello,

We are working to solve this issue. We will inform you as soon as we have a solution for it.

**Comment by vladasdrejeris** [comment]
Hello,

I am unable to reproduce your issue. 
Maybe you could make a sample project containing the issue you described and attach it here?

**Comment by vladasdrejeris** [comment]
If this issue is still occurring for you, try setting different banner loading behavior, like this:

```
[AdformSDK setBannerLoadingBehaviour: AFBannerLoadingBehaviourInstant];
```
