### ISSUE TITLE
adv delivered with wrong size

### ISSUE THREAD

**Issue by adegrawebpills** [adform/adform-ios-sdk#19]
Hello we are using your SDK on our application but the size of the adv delivered is wrong what can we do?

**Comment by andriusmisiunas** [comment]
Hello,

Is this the same issue as described here? https://github.com/adform/adform-ios-sdk/issues/8

**Comment by vladasdrejeris** [comment]
Hello,

Could you describe your problem in more detail? How are you integrating Adform SDK? What size are you expecting and what size do you get? Are you setting custom ad size or using the default ones?

**Comment by adegrawebpills** [comment]
Hello the problem is similar but is not the same described at #8
we aspect two different size of ADV 300x250 - 320x250 
in both case the return is a small adv I can't mesure it... but it's 1/3 smaller more less

**Comment by vladasdrejeris** [comment]
Hello,

Could you provide us with your ad implementation code? 
Or attach a sample project with the described problem?
