### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by notincoming** [adform/adform-ios-sdk#20]
Hello, I have tried to launch adform service on iPhone 6s with iOS 11.2.1 in debug mode.
Anytime I recieve Unsuported URL error.
Plist:
![zrzut ekranu 2018-01-13 o 09 46 07](https://user-images.githubusercontent.com/14039590/34904524-eae61b3a-f847-11e7-9472-2aa9c435854a.png)

Code:
![zrzut ekranu 2018-01-13 o 09 42 51](https://user-images.githubusercontent.com/14039590/34904503-93cfa528-f847-11e7-8747-8ac0dd5ba84e.png)

Error:
![zrzut ekranu 2018-01-13 o 09 43 01](https://user-images.githubusercontent.com/14039590/34904504-a1d69316-f847-11e7-98c4-dd38b9532552.png)

Why is it happening all the time?
I am waiting to hear from you,
Aleksander.

**Comment by vladasdrejeris** [comment]
Hello,

You should never use `debugMode`. This property is intended for internal usage only. Sorry if this has misled you.

**Comment by notincoming** [comment]
So how I am supposed to watch an add while I am testing an application?
I have tried to open something also without debug mode but still without any appropriate result, only with information that add has not been loaded.
I am waiting to hear from you,
Aleksander.

**Comment by vladasdrejeris** [comment]
Is your master tag configured correctly?

**Comment by notincoming** [comment]
I receive my master tag from my project manager so I expect that this is configured correctly.
As the proof I can say, that it works on the android platform.
Also I've tried with master tag placed in the sample app, but still without good result.

**Comment by vladasdrejeris** [comment]
Maybe you could make a new project with only the integration of the Adform SDK that reproduces you issue and attach it here? I would take a look and try to figure out what is wrong.

**Comment by notincoming** [comment]
https://github.com/notincoming/AddFormTest 
I am waiting to hear from you,
Aleksander.

**Comment by notincoming** [comment]
Hello, is there any progress?
I am waiting to hear from you,
Aleksander.

**Comment by vladasdrejeris** [comment]
Hello, 

Try it now, banners are being loaded for mtag 142493.

**Comment by notincoming** [comment]
Now it looks fine for your mtag:
![27048308_1916156611746209_1998529310_o](https://user-images.githubusercontent.com/14039590/35227090-6d59b166-ff8d-11e7-8d4e-cb876fedb00b.jpg)

For my tag I still have error with information "no adds to show".

**Comment by notincoming** [comment]
Now it's almost good. Add is loading only when "additional dimensions" flag is on, when I turn it off then nothing happens again, also the size is not as it is desired.
During any frame operations, there is no influence on the add size.

On addInlineDidLoad I am receiving proper frame 320 x 50, but after loading a real frame is (0 0; 320 250), also any add is visible only for the sample app master tag.

I am waiting to hear from you,
Aleksander.

**Comment by vladasdrejeris** [comment]
If "additional dimensions" flag is on, then the ad view is resized to match the size of the banner retrieved from the server.

If "additional dimensions" flag is off, then ad exchange server tries to return a banner whose size matches the size of the placement (ad view), by default placement size is 320x50, you can also set a custom ad size.
For this to work correctly, you need to configure a placement with this size in Adform console.

Also, sample app master tag loads ads with size 320x250.

**Comment by notincoming** [comment]
OK, I will try to haste somebody with the console access.
Thank you for the reply.

Best regards,
Aleksander.

**Comment by Adform-Support** [comment]
Hello @notincoming,

This is Adform Publishers support team.
If you will need any help regarding placement configuration, please contact us publishers@adform.com and we will help you out :)

Best regards,
Laurynas
