### ISSUE TITLE
Get ad size before it gets loaded ( before loadAd() )

### ISSUE THREAD

**Issue by rogierdna** [adform/adform-ios-sdk#23]
Hello, we need a little help with ad sizes

in Placement configuration we have this setting.
![image](https://user-images.githubusercontent.com/17268723/37342696-04cded34-26ce-11e8-999e-52a201a99aab.png)

in app using code:
(when initialising CellNode in tableView)
We use this code to load the ad via adform-ios-sdk
```
let adView = AFAdInline(masterTagId: mTag, presenting: self.controller)
adView?.delegate = self
adView?.debugMode = true

print("adSize \(adView?.adSize)")
		
adView?.loadAd()
return adView!
```

So here we get the banner loaded but we do not know its size before it gets loaded.
_Is it possible to get that size before ad loads?_

`adView?.adSize`

Also if we try get the adSize after loading then the adSize value is not the size set in Dimensions field. Nor it is the size of the ad loaded.

Also when checking from `adInlineDidLoadAd` delegate method the value of adInline.adSize is also not the size of loaded ad

```
    func adInlineDidLoadAd(_ adInline: AFAdInline!) {
        print("adHeight \(adInline.adSize)")
    }
```
same issue with `adInlineWillShow`, the result is not the size set in placement config

Any help is appreciated.

**Comment by vladasdrejeris** [comment]
Hello,

You should not use: 
```obj-c
adView?.debugMode = true
```
This property is intended only for internal usage by Adform.
Also, you should set ad size 600x500 on adView, because you are using this size in placement configuration.
If you want to load banners with different sizes in one adView, you should use additionalDimensions instead.
