### ISSUE TITLE
Opening banner target URLs

### ISSUE THREAD

**Issue by rogierdna** [adform/adform-ios-sdk#24]
How to control where and how to open banner target URL’s?
currently clicking on some banner opens some webpage in external browser.
How to open that webpage in in-app browser? 
I guess we need to be able to intercept the click (we use delegate method and it is working) and then get the targetURL to decide what to do with it. Currently looks liek there is no way to get the targetURL from ADInline object passed into delegate method.
I’m browsing the AdInline docs but looks like i’m there is no info on that, at least i have not find it yet.
Any suggestions?

**Comment by vladasdrejeris** [comment]
Hello,

You should use `AdformSDK` class method:

```
+ (void)setOpenLinksInAppBrowser:(BOOL )shouldOpen;
```

**Comment by rogierdna** [comment]
Thank you, will try it out.

**Comment by rogierdna** [comment]
So when I use:
`AdformSDK.setOpenLinksInAppBrowser(true)`
then, when banner is clicked it returns such log:
`Warning: Attempt to present <AFSafariViewController: 0x1069a2000> on <UIViewController: 0x105dcb180> whose view is not in the window hierarchy!`

What is `AFSafariViewController` and where and how can I initialize it?
Searching on docs does not return any results on 'AFSafariViewController'.

Just to note, UIViewController which is not in hierarchy is the dummy controller as the AdView is created inside Texture node.

Could you please point in docs or provide a sample code on how to intercept the targetURL of the banner provided via AdformSDK ?

**Comment by rogierdna** [comment]
@vladasdrejeris OK, I got the in-app browser working by replacing the dummy controller with current root controller.
But I'm still unable to intercept the targetURL's

**Comment by vladasdrejeris** [comment]
Currently there is no way for the app to intercept these URL's.
