### ISSUE TITLE
language localization in sdk

### ISSUE THREAD

**Issue by umutkina** [adform/adform-ios-sdk#27]
in the SDK, we couldn't find any language option, for Video Ad Integration "skip" text. does the text in the SDK change according to device language. if it is not possible is there any way to change texts in the SDK.

**Comment by umutkina** [comment]
in the SDK, we couldn't find any language option, for Video Ad Integration "skip" text. does the text in the SDK change according to device language. if it is not possible is there any way to change texts in the SDK.

**Comment by andriusmisiunas** [comment]
Localization has been added in version 2.13.2:
https://github.com/adform/adform-ios-sdk/releases/tag/v.2.13.2
Usage:
https://github.com/adform/adform-ios-sdk/wiki/Localization
