### ISSUE TITLE
AFAdInline in scroll view scrolls itself if the navigation bar is translucent

### ISSUE THREAD

**Issue by BozhkoAlexander** [adform/adform-ios-sdk#29]
Hi! I have a problem with AFAdInline inside UITableViewCell. When I scroll the table view and ad starts to leave the screen, it starts to scroll itself to bottom to 64px (navigation bar height). If I set isTranslucent property of navigationBar to false, all works properly (without any additional scrolls). So, me question is: how to disable this behaviour of AFAdInline view for view controllers with translucent navigation bar?

**Comment by vladasdrejeris** [comment]
Hi,
Maybe you constraint ad view to safe area and not to superview?

**Comment by BozhkoAlexander** [comment]
I don't think so. I do nothing else except this:

    // My UITableViewCell subclass

    var ad: Ad! = nil
    var adView: AFAdInline! = nil

    func update(_ ad: Ad, vc: UIViewController) {
        adView = Ad.inline(for: ad.place, with: ad.id, viewController: vc)
        if adView != nil {
            let k = contentView.bounds.width / ad.width
            adView.transform = CGAffineTransform(scaleX: k, y: k)
            contentView.addSubview(adView)
        }
        self.ad = ad
        self.setNeedsLayout()
    }

    override func layoutSubviews() {
        super.layoutSubviews()
        
        var size = contentView.bounds.size
        if adView != nil {
            if let width = ad?.width {
                size.width = width
            }
            if let height = ad?.height {
                size.height = height
            }
            adView?.frame.size = size
            adView?.frame.origin = .zero
        }
    }

**Comment by vladasdrejeris** [comment]
Hi again, I am unable to reproduce your problem. 
Maybe you could create and share a sample project containing this problem?

**Comment by vladasdrejeris** [comment]
Hello,
You haven't yet provided us with a sample project, so we are wondering if you are still having this issue or perhaps you have already solved it yourself?

**Comment by BozhkoAlexander** [comment]
Hello, I’m sorry I didn’t notify you.

Yes, I’ve solved this issue myself. The problem was in my view controller code which overrides some of scroll view delegate methods. 
Thank you for the answer!

**Comment by vladasdrejeris** [comment]
I am glad to hear that your issue is solved.
