### ISSUE TITLE
Attempt to obtain CGRect from NSValue containing {CGPoint=dd}

### ISSUE THREAD

**Issue by Gerharbo** [adform/adform-ios-sdk#30]
Hi,

We're updating an existing app and we use `AdformAdvertising 2.13.3`. The following came to my attention when I add a `AFAdInline` and try to load a banner:

```
 [UIKit] Attempt to obtain CGRect from NSValue containing {CGPoint=dd}: NSPoint: {0, 0}. In future versions this will throw an exception. Returning empty values.
```

**Comment by vladasdrejeris** [comment]
Hello,

This issue has been fixed in 2.13.5 SDK version.
