### ISSUE TITLE
Fetch SDK via carthage does not work

### ISSUE THREAD

**Issue by NavPatrik** [adform/adform-ios-sdk#32]
Used this in cartfile:
`binary "https://raw.githubusercontent.com/adform/adform-ios-sdk/master/AdformAdvertising.json" ~> 2.13.4`
as instructed from 
https://github.com/adform/adform-ios-sdk/wiki/Getting-Started#23-using-carthage
but I get
`*** Downloading binary-only framework AdformAdvertising at "https://raw.githubusercontent.com/adform/adform-ios-sdk/master/AdformAdvertising.json"
No tagged versions found for binary "https://raw.githubusercontent.com/adform/adform-ios-sdk/master/AdformAdvertising.json"
`
when trying to fetch the dependency

**Comment by vladasdrejeris** [comment]
Hello,

Sorry for the inconvenience. I have fixed this issue and carthage integration works as expected now.
