### ISSUE TITLE
SDK 2.20.0 does not compile on Xcode 13.4.1

### ISSUE THREAD

**Issue by marcin-bo** [adform/adform-ios-sdk#35]
Hi,

I use Swift Package Manager to integrate the SDK with my project. When I try to compile SDK 2.20.0 on Xcode 13.4.1 I get hundreds of errors (see the image below). SDK 2.19.1 does compile on Xcode 13.4.1.

<img alt="Zrzut ekranu 2023-01-31 o 16 53 20" src="https://user-images.githubusercontent.com/26303487/215810482-5224f32b-b040-44ca-89b4-e46a86971c80.png" width="400">

**Comment by vladasdrejeris** [comment]
Hello,

Thank you for reaching out.
2.20.0 SDK version is built with Xcode 14 and Xcode 14 no longer supports armv7 architecture (https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes). Therefore, you are seeing missing symbol warnings. You should update your Xccode or continue using 2.19.1 SDK version until you do so.

**Comment by marcin-bo** [comment]
Thanks!
