### ISSUE TITLE
arbitrary loads for App Transport Security no longer viable

### ISSUE THREAD

**Issue by palmin** [adform/adform-ios-sdk#5]
Apple has announced that App Transport Security will be a requirement from January 2017.
    https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/

Just having a configuration in the Info.plist that allows arbitrary loads will be causing problems with App Review in just a months time. 

Please provide more fine-grained exceptions to App Transport Security, that only allow using http with specific servers.

**Comment by vladasdrejeris** [comment]
Hi,

Our SDK uses secure HTTPS protocol for network communications, therefore there is no need to disable ATS for it.

**Comment by palmin** [comment]
That is great. I was just confused by the sample application that entirely disabled ATS.

**Comment by vladasdrejeris** [comment]
That config must have stayed there from an older version. Thanks for noticing us, we will update the sample application.
