### ISSUE TITLE
Built SDK is missing arm64 architecture

### ISSUE THREAD

**Issue by Auralien** [adform/adform-ios-sdk#6]
I'm following installation instructions for the case of [manual installation](https://github.com/adform/adform-ios-sdk/wiki/Getting-Started#22-manually). When trying to build the project after that I get this error message:
```
Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_SFSafariViewController", referenced from:
      _OBJC_METACLASS_$_AFSafariViewController in AdformAdvertising(AFSafariViewController.o)
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in AdformAdvertising(AFUtilities.o)
      _OBJC_CLASS_$_AFSafariViewController in AdformAdvertising(AFSafariViewController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I remove `arm64` from `Valid Architectures` I get same message about `armv7`:
```
Undefined symbols for architecture armv7:
  "_OBJC_METACLASS_$_SFSafariViewController", referenced from:
      _OBJC_METACLASS_$_AFSafariViewController in AdformAdvertising(AFSafariViewController.o)
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in AdformAdvertising(AFUtilities.o)
      _OBJC_CLASS_$_AFSafariViewController in AdformAdvertising(AFSafariViewController.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The issue is reproducible on a clean Objective-C project with added Swift code: I've created a single view application in ObjC and then added a Swift view controller from which I'm trying to call the Adfrom code.

Example project is attached.
[AdformObjcTestApp.zip](https://github.com/adform/adform-ios-sdk/files/716860/AdformObjcTestApp.zip)

**Comment by vladasdrejeris** [comment]
Hello, 

You need to import SafariServices.framework.

**Comment by Auralien** [comment]
Please add this info to the Wiki.
