### ISSUE TITLE
Placement refresh in iOS SDK Adform

### ISSUE THREAD

**Issue by Marknolby** [adform/adform-ios-sdk#7]
Hi. Could I get some help regarding refresh rate on placements through the Adform SDK.
Is there a possibility to create behaviour in the SDK to refresh placements for inline banner types.

**Comment by andriusmisiunas** [comment]
Hello,
This functionality should be supported via Adform internal system for AdHesion type ads - not the SDK itself. Please let us know if this solves the issue.
