### ISSUE TITLE
Feature request: stretch Ad to fit container width and maintain original aspect ratio

### ISSUE THREAD

**Issue by michal-maciag** [adform/adform-ios-sdk#8]
Hi, we have a feature request for the SDK team. 
We're showing the Ads as a row/cell in UITableView and we want the Ad to stretch itself to fill the whole available width.
For example the Ad placement is defined as 320x160 and we're loading it on 4.7" iPhone (6/6s/7) with a UITableViewCell size of 375x187.5 points. We would like the Ad to stretch itself, given the available frame to fit the whole width. 
Currently we have two options. One is to use the base size (320x160), leaving empty space around the Ad. The other is to use the AFSmartAdSize, but the problem is that in this case the height is either 50 or 90 points (depending on device screen height). Which in turns leaves even more empty space, since the Ad actually shrinks from 320x160 to 100x50. 
I can attach an example project with our setup if you need it.

**Comment by ivenckus** [comment]
Hi @deveniro,

Thanks for request. It would be interesting to know publisher/app name where you are going to use Adform SDK. And yes, example project would help a lot.

Thanks

**Comment by michal-maciag** [comment]
Hi @ivenckus,
Please find the attached zip file with the sample project. It is best to run it on iPhone 6/6s/7 or their 'Plus' counterparts. I suggest using iPhone 7 simulator.  
The sample app was created from your own sample available on this site. However I did remove most of the original app and currently only left our own implementation. 
We are using AsyncDisplayKit's ASTableView, the setup and behaviour is very similar to a regular UITableView. 
You can see 5 cells with banners, the first two are created with frames that span across whole width with adjusted height (we keep the original aspect ratio). 
Next two banners, are simply centered in their respectful frames, also the cell's height is not extended (as opposed to the first two cells). 
The last banner uses SmartAdSize, just to visualise why this solution doesn't really work for us. 
[adform-ios-sdk-sample.zip](https://github.com/adform/adform-ios-sdk/files/854490/adform-ios-sdk-sample.zip)

What we would like to achieve is to have the banners from the first two cases to stretch to fit the desired frame (the frame's background is marked in purple, to help visualise the space we want to use). Since the app can be run on different devices (i.e iPhone 7, 7+ or even iPad, although the iPad case is different, as the table doesn't use the whole available width, it's more similar to iPhone 6/7 actually).

**Comment by michal-maciag** [comment]
Hi again, 
any new thoughts on this issue?

**Comment by andriusmisiunas** [comment]
Hello,

Sorry for a huge delay - there was an ownership change of the project within the organisation and the SDK was unattended for a while. We checked the test app and it seems that the tags are no longer active. @deveniro, could they be reactivated so we could check further?
Tags IDs are: 103262, 99200, 103262, 99200, 103262.

Thanks!

**Comment by michal-maciag** [comment]
Hi, 
we have restored the master tags, so you should be able to see the banners in the sample app. 
Let me know if you need some more help with the sample app or something is not working for you. 
Thanks for looking into this!

**Comment by vladasdrejeris** [comment]
Hello,

Setting a bigger frame doesn't scale the banner, only option at the moment to do it is to use transformation. I have updated your sample app to use it on the web node, take a look
[adform-ios-sdk-master-updated.zip](https://github.com/adform/adform-ios-sdk/files/1145001/adform-ios-sdk-master-updated.zip).

**Comment by vladasdrejeris** [comment]
I have hardcoded the scale values in sample, but you should calculate them based on device screen and ad sizes.
