### ISSUE TITLE
Problem displaying interstitial. Error-message: Ad is not loaded

### ISSUE THREAD

**Issue by sil-visiolink** [adform/adform-ios-sdk#9]
I've encountered an issue when trying to display an AFAdInterstitial. I'm using an UIView as ad container and attaches the AFAdInterstitial to this view.

The delegate method adInlineDidLoadAd is called, so it should be loaded and ready to display. This is not the case however.

The initial setup of the interstitial is implemented as depicted below:
```
self.adInterstitial = [[AFAdInterstitial alloc] initWithAdTag:ad.masterTag presentingViewController:ad.adProviderDelegate];
    VLViewController *controller = (VLViewController *)ad.adProviderDelegate;
    self.adInterstitial.frame = controller.view.frame;
    [self.adInterstitial setShowAdAutomatically:NO];
    self.adInterstitial.delegate = self;
    self.adInterstitial.autoresizingMask = (UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth);
    self.adInterstitial.translatesAutoresizingMaskIntoConstraints = YES;
    self.adInterstitial.keyValues = AFKeyValuesFromNSDictionary(ad.keyValues);
    [self addSubview:self.adInterstitial];
    
    [self.adInterstitial loadAd];
```

The exact error message is:
<error> Cannot show the ad view: <AFAdInterstitial: 0x7ff729f7e090; frame = (0 0; 1024 768); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x608000453da0>; layer = <CALayer: 0x61800003a900>>, ad is not loaded!

**Comment by vladasdrejeris** [comment]
Hello,

When and were are you calling "showAd" method?

**Comment by sil-visiolink** [comment]
It's called when the specific page is about to be shown. The dummy ad is a placeholder with information regarding the page specific ad. So it contains the keyvalues, the master tag and the page number.

```
// This is called when the ad is about to be presented
-(UIView*) getInterstitialViewForAd: (id<VLAdObject>) adObject
                           customer: (NSString*) customer
                             folder: (NSInteger) folder
                            catalog: (NSInteger) catalog
                               page: (NSInteger) page
                        orientation: (UIInterfaceOrientation) orientation {
    
    VLAdformDummyAd *ad = (VLAdformDummyAd*) adObject;
    
    UIView *containerView = [self.adProviderDelegate adContainerView];
    
    VLAdformAdView *interstitialView = nil;
    
    if (ad == self.frequencyDisplayedAd) {
        interstitialView = (VLAdformAdView *)self.frequencyDisplayedAdView;
    }
    else if (ad.page == self.currentlyLoadingForPage) {
        interstitialView = (VLAdformAdView *)self.pageSpecificAdView;
    }
    
    interstitialView.frame = containerView.bounds;
    [interstitialView.adInterstitial showAd];
    
    return interstitialView;
}
```

**Comment by vladasdrejeris** [comment]
Make sure that you are not calling "showAd" before the ad was loaded. You can show the ad only after you get a callback to "adInlineDidLoadAd" delegate method.

**Comment by sil-visiolink** [comment]
If I use the debugger and call po [interstitialView.adInterstitial isLoaded] in the debugger it returns "YES".

So [interstitialView.adInterstitial showAd] should be good to go, as far as I can see. Sometimes it doesn't give the error but the ad is still not shown.

**Comment by vladasdrejeris** [comment]
Try to use this initializer: 
- (instancetype)initWithFrame:(CGRect )frame masterTagId:(NSInteger)mid presentingViewController:(UIViewController *)viewController;

**Comment by sil-visiolink** [comment]
If I change it to that the adInlineDidLoadAd delegate method isn't called - which is quite strange. If I use the other initializer and set the frame afterwards it is called...

**Comment by vladasdrejeris** [comment]
Maybe you aren't getting any ads with the master tag id that you use.
The initializer that I posted earlier is intended for the Interstial ads and you should use it.
You may try your master tag id on our sample application and check if interstitial ads are loaded correctly there.

**Comment by sil-visiolink** [comment]
![screen shot 2017-04-06 at 13 26 09](https://cloud.githubusercontent.com/assets/6650000/24752069/a18f06ee-1acc-11e7-86d2-b2c956a5696e.png)

This is the interstitial in the sample app.

**Comment by vladasdrejeris** [comment]
Are you setting key values in sample application too?

Maybe there are some more code related to the adInterstitial implementation in you project?

**Comment by sil-visiolink** [comment]
Yes, I'm also setting the key values in the sample application. Is it possible to tap in on the ad request, so I can call the URL in a browser and see what is returned?

**Comment by vladasdrejeris** [comment]
I am sorry, but it is not possible. 
Maybe you could make a sample project with the same issue and send it to me? I would take a look. My email: vladas.d@ito.lt .

**Comment by sil-visiolink** [comment]
Hmm this is strange. I turned on debug-mode, and now I see this banner: 
![screen shot 2017-04-10 at 11 12 58](https://cloud.githubusercontent.com/assets/6650000/24854420/b0ec3322-1dde-11e7-9307-1fee873ad4d4.png)

**Comment by sil-visiolink** [comment]
Sure I'll zip the sample project with the key-values and master-tags embedded.

**Comment by vladasdrejeris** [comment]
Don't use debug mode, its not meant for production use.

**Comment by vladasdrejeris** [comment]
But this sample project is loading ads. Maybe you could make a sample project with your own implementation that is not loading the ads and send it to me?

**Comment by sil-visiolink** [comment]
Hi,

Could you send me a screenshot of what the ad looks like? I would love to know what I’m actually looking for.

**Comment by vladasdrejeris** [comment]
I am seeing this ad in sample application with your master tag:
![screen shot 2017-04-10 at 13 04 58](https://cloud.githubusercontent.com/assets/7370193/24856738/7209e662-1dee-11e7-918b-97a20d3dd599.png)

**Comment by sil-visiolink** [comment]
Yes I get the same result in the sample app. I was just in doubt if this was the right one because of the question mark in the top left corner.

It’s not possible for me to make a closed project with my own implementation. I can send you the class where I create the adform. The class that calls it however is part of the backbone of all of our apps and is confidential.

**Comment by vladasdrejeris** [comment]
I understand, then send me the class that you can share, maybe I will find something out there.

**Comment by vladasdrejeris** [comment]
FIrst of all, why are you making a subclass of AFAdInterstitial?
Secondly, you should use different initializer as I said before.
Other than that the code looks ok.
You should also check with debuger if all the frames are correct and you can try to enable autoshow on ads just to see if it makes any difference.
Or you can try to just add an interstitial ad to a view controller and try to load it with your parameters to see if it will load.

**Comment by sil-visiolink** [comment]
Thank you for your input.

If I change the initializer to:

self.adInterstitial = [[AFAdInterstitial alloc]  initWithFrame:[[controller adContainerView] frame] masterTagId:ad.masterTag presentingViewController:ad.adProviderDelegate];

Then the delegate method isn’t called anymore.

The frame I’m initializing it is:
(0 0; 1024 768) – so that should be good.

Do you have an explanation as to why the delegate method isn’t called when I switch to the initializer above?
Best Regards / Mit freundlichen Grüßen / Med venlig hilsen
[cid:image001.png@01D2B213.C9499090]

Simon Lauridsen

Technical Design Engineer

m: +45 26855496    p: +45 7023 3544
a: Bjoernholms Allé 20, DK-8260 Viby J

w: visiolink.com<http://visiolink.com/>



Want to read about updates on Digital Publishing – see our blog!<http://blog.visiolink.com/>

**Comment by vladasdrejeris** [comment]
Maybe you are getting some kind of error?

**Comment by sil-visiolink** [comment]
Hi,

The error stated that the ad couldn’t load because it didn’t have a master tag. I realised the masterTag was a string.. So now I’ve changed it to an NSInteger and I see the ad!

Thank you so much for your help, it saved me a lot of time!

**Comment by vladasdrejeris** [comment]
Hi,
Good to hear that you were able to solve the problem.
